Error in results$se[!is.na(reg9$beta)] <- reg2$ses : 
  object 'reg9' not found


Error in results$se[!is.na(reg9$beta)] <- reg2$ses : 
  object 'reg9' not found


Error in base::try(z, silent = TRUE) : object 'z' not found


<text>:1:6: unexpected '{'
1: .pkg {
         ^

Error in cpp_demean(y, X, weights, iterMax = iter, diffMax = tol, r_nb_id_Q = fixef_sizes,  : 
  cpp_demean: User interrupt.


Error in base::try(pen_bic, silent = TRUE) : object 'pen_bic' not found


Error in cpp_demean(y, X, weights, iterMax = iter, diffMax = tol, r_nb_id_Q = fixef_sizes,  : 
  cpp_demean: User interrupt.


<text>:1:6: unexpected '{'
1: .pkg {
         ^

