# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMatMult <- function(A, B) {
    .Call(`_penpplm_eigenMatMult`, A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_penpplm_eigenMapMatMult`, A, B)
}

fastolsCpp <- function(X, y) {
    .Call(`_penpplm_fastolsCpp`, X, y)
}

fastridgeCpp <- function(X, y, lambda) {
    .Call(`_penpplm_fastridgeCpp`, X, y, lambda)
}

faststddev <- function(X, w) {
    .Call(`_penpplm_faststddev`, X, w)
}

fastwmean <- function(X, w) {
    .Call(`_penpplm_fastwmean`, X, w)
}

manyouter <- function(A, B, c) {
    .Call(`_penpplm_manyouter`, A, B, c)
}

xeex <- function(X, ee) {
    .Call(`_penpplm_xeex`, X, ee)
}

