# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMatMult <- function(A, B) {
    .Call(`_penppml_eigenMatMult`, A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_penppml_eigenMapMatMult`, A, B)
}

fastolsCpp <- function(X, y) {
    .Call(`_penppml_fastolsCpp`, X, y)
}

fastridgeCpp <- function(X, y, lambda) {
    .Call(`_penppml_fastridgeCpp`, X, y, lambda)
}

faststddev <- function(X, w) {
    .Call(`_penppml_faststddev`, X, w)
}

fastwmean <- function(X, w) {
    .Call(`_penppml_fastwmean`, X, w)
}

manyouter <- function(A, B, c) {
    .Call(`_penppml_manyouter`, A, B, c)
}

xeex <- function(X, ee) {
    .Call(`_penppml_xeex`, X, ee)
}

